version: '3.8'
services:
  worker:
    build: .
    container_name: worker-app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - REDIS_URL=redis://default:GpDu8KYKJRJYcPVDZDCJ6D9NWZRyHspO@redis-16707.crce197.us-east-2-1.ec2.redns.redis-cloud.com:16707
    restart: unless-stopped
    healthcheck:
      test: [
        "CMD",
        "node",
        "-e",
        "require('http').get('http://localhost:4000/schedule', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
