version: '3.8'

services:
  worker:
    build: .
    container_name: snipesend-worker-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: [
        "CMD",
        "node",
        "-e",
        "require('http').get('http://localhost:4000/schedule', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
