services:
  - type: worker
    name: email-worker
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: REDIS_URL
        value: redis://default:GpDu8KYKJRJYcPVDZDCJ6D9NWZRyHspO@redis-16707.crce197.us-east-2-1.ec2.redns.redis-cloud.com:16707
      - key: PORT
        value: 4000
